version : "3.7"
services :
  proyectos_monolito :
    container_name : proyectos-micro
    image : proyectos-micro:v1
    build :
      context: .
    ports:
      - "4001:4001"
    networks :
      - proyectos-app
networks :
  proyectos-app:
      
       